# Автоматический деплой ESG-Lite на VM2
name: Deploy to VM2

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  deploy:
    name: Deploy to VM2
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Увеличиваем таймаут до 20 минут
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VM2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM2_HOST }}
        username: ${{ secrets.VM2_USER }}
        key: ${{ secrets.VM2_SSH_KEY }}
        port: 22
        timeout: 15m  # Таймаут SSH соединения
        command_timeout: 10m  # Таймаут для отдельных команд
        script: |
          echo "🚀 Начинаем деплой ESG-Lite..."
          
          # Переходим в директорию проекта
          cd /opt/esg-lite || { echo "❌ Директория /opt/esg-lite не найдена"; exit 1; }
          
          # Создаем локальные SSL сертификаты если их нет
          if [ ! -f ./ssl/nginx-selfsigned.crt ]; then
            echo "🔐 Генерируем SSL сертификат..."
            mkdir -p ./ssl
            openssl genrsa -out ./ssl/nginx-selfsigned.key 2048
            openssl req -new -x509 -key ./ssl/nginx-selfsigned.key \
              -out ./ssl/nginx-selfsigned.crt -days 365 \
              -subj "/C=RU/ST=Moscow/L=Moscow/O=ESG-Lite/CN=82.202.156.35"
            chmod 600 ./ssl/nginx-selfsigned.key
            chmod 644 ./ssl/nginx-selfsigned.crt
          fi
          
          # Останавливаем контейнеры
          echo "⏹️ Останавливаем контейнеры..."
          docker compose -f docker-compose.prod.yml down
          
          # Обновляем код
          echo "📥 Обновляем код из GitHub..."
          git fetch origin
          git reset --hard origin/main
          
          # Проверяем что authorized_key.json существует
          if [ ! -f authorized_key.json ]; then
            echo "⚠️ authorized_key.json не найден, но это нормально для безопасности"
          fi
          
          # Удаляем старые образы
          echo "🧹 Очищаем старые образы..."
          docker image prune -f
          
          # Собираем и запускаем новые контейнеры (с оптимизацией)
          echo "🔨 Собираем и запускаем контейнеры..."
          DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker compose -f docker-compose.prod.yml up -d --build --parallel
          
          # Применяем миграции базы данных
          echo "🗃️ Применяем миграции базы данных..."
          docker compose -f docker-compose.prod.yml exec -T esg-lite-web sh -c 'DATABASE_URL="${{ secrets.PRODUCTION_DATABASE_URL }}" npx prisma migrate deploy'
          
          # Проверяем актуальность коэффициентов 296-ФЗ
          echo "📊 Проверяем актуальность коэффициентов выбросов..."
          docker compose -f docker-compose.prod.yml exec -T esg-lite-web sh -c 'node scripts/update-emission-factors.js --check || echo "⚠️ Коэффициенты требуют обновления после деплоя"'
          
          # Ждем запуска
          echo "⏳ Ждем запуска сервисов..."
          sleep 30
          
          # Проверяем статус
          echo "✅ Проверяем статус контейнеров..."
          docker compose -f docker-compose.prod.yml ps
          
          # Проверяем логи
          echo "📋 Последние логи:"
          docker compose -f docker-compose.prod.yml logs --tail=20
          
          echo "🎉 Деплой завершен!"

    - name: Health Check
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM2_HOST }}
        username: ${{ secrets.VM2_USER }}
        key: ${{ secrets.VM2_SSH_KEY }}
        port: 22
        script: |
          cd /opt/esg-lite
          echo "🏥 Проверяем здоровье приложения..."
          
          # Ждем полного запуска
          sleep 60
          
          # Диагностика контейнеров
          echo "🔍 Проверяем статус контейнеров..."
          docker compose -f docker-compose.prod.yml ps
          
          echo "🔍 Проверяем какие порты слушаются..."
          ss -tlnp | grep -E ":80|:443|:3000" || netstat -tlnp | grep -E ":80|:443|:3000" || echo "Порты не найдены"
          
          # Проверяем доступность приложения через nginx
          if curl -f -k https://localhost/api/queue/health; then
            echo "✅ Приложение работает корректно!"
            echo "🌐 Сайт доступен по адресу: https://esg-lite.ru"
          else
            echo "❌ Приложение недоступно через nginx, проверяем напрямую контейнер..."
            if docker compose -f docker-compose.prod.yml exec -T esg-lite-web curl -f http://localhost:3000/api/queue/health; then
              echo "⚠️ Веб-контейнер работает, но nginx не проксирует"
            else
              echo "❌ Веб-контейнер не отвечает"
            fi
            echo "📋 Логи контейнеров:"
            docker compose -f docker-compose.prod.yml logs --tail=50
            exit 1
          fi

    - name: Notify Success
      if: success()
      run: |
        echo "🎉 Деплой на VM2 успешно завершен!"
        echo "🌐 Приложение доступно по адресу: https://esg-lite.ru"

    - name: Notify Failure
      if: failure()
      run: |
        echo "❌ Деплой на VM2 завершился с ошибкой!"
        echo "🔍 Проверьте логи выше для диагностики проблемы"