# Lighthouse CI для тестирования производительности
# Обновлено для Next.js 15.4.5, Node.js 22.18.0 LTS (Август 2025)
name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'  # Обновлено для Node.js 22.18.0 LTS
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify Next.js 15.4.5 build
      run: |
        echo "🔍 Verifying Next.js build with new features..."
        npm run build
        
    - name: Check build output
      run: |
        echo "📊 Build analysis:"
        ls -la .next/
        du -sh .next/
        
    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.12.x
        lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        
    - name: Upload Lighthouse results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lighthouse-results
        path: .lighthouseci/
